name: The Sarah Pratt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#016948'
    - '#899d44'
    - '#94d1e3'
    - '#013940'
  brandStrength: 0.5625
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
